#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path('../lib', __dir__)
require 'polites'
require 'polites/cli'

Polites::Cli.new(stdin: $stdin, stdout: $stdout).call(ARGV)
